# -*- coding: utf-8 -*-
"""agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTiFX68wDyNYw140jo9EuqUo2r17RkRq
"""

from langchain.agents import initialize_agent, Tool
from langchain.chat_models import ChatOpenAI
from datetime import datetime
from calendar_service import check_availability, book_appointment

def check_calendar_tool(time_str: str) -> str:
    try:
        dt = datetime.fromisoformat(time_str)
        is_free = check_availability(dt)
        return "Available ✅" if is_free else "Not available ❌"
    except Exception as e:
        return f"Error checking: {e}"

def book_calendar_tool(time_str: str) -> str:
    try:
        dt = datetime.fromisoformat(time_str)
        url = book_appointment(dt)
        return f"Booked! 📅 Here’s your link: {url}"
    except Exception as e:
        return f"Booking failed: {e}"

tools = [
    Tool(name="CheckAvailability", func=check_calendar_tool, description="Check if a datetime is free (ISO format)."),
    Tool(name="BookAppointment", func=book_calendar_tool, description="Book an appointment (ISO format).")
]

llm = ChatOpenAI(temperature=0)

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent="chat-zero-shot-react-description",
    verbose=True
)

def chat_with_agent(user_input: str):
    return agent.run(user_input)