# -*- coding: utf-8 -*-
"""calendar_service

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15x1RwGfXuKbRAr-yU0KbEvwSc3NdSd6g
"""

import os
import json
from datetime import datetime, timedelta
from google.oauth2 import service_account
from googleapiclient.discovery import build

# Load credentials (from file locally, from env in production)
if os.path.exists("service_account.json"):
    credentials = service_account.Credentials.from_service_account_file(
        "service_account.json",
        scopes=["https://www.googleapis.com/auth/calendar"]
    )
else:
    service_account_info = json.loads(os.environ["SERVICE_ACCOUNT_JSON"])
    credentials = service_account.Credentials.from_service_account_info(
        service_account_info,
        scopes=["https://www.googleapis.com/auth/calendar"]
    )

# Build calendar service
calendar_service = build("calendar", "v3", credentials=credentials)

CALENDAR_ID = "jhasneha344@ggmail.com"

def check_availability(start_time: datetime, duration_minutes: int = 30):
    end_time = start_time + timedelta(minutes=duration_minutes)
    body = {
        "timeMin": start_time.isoformat() + "Z",
        "timeMax": end_time.isoformat() + "Z",
        "items": [{"id": CALENDAR_ID}]
    }
    events = calendar_service.freebusy().query(body=body).execute()
    busy = events["calendars"][CALENDAR_ID]["busy"]
    return not busy  # True if available

def book_appointment(start_time: datetime, summary="TailorTalk Appointment", duration_minutes=30):
    end_time = start_time + timedelta(minutes=duration_minutes)
    event = {
        "summary": summary,
        "start": {"dateTime": start_time.isoformat(), "timeZone": "UTC"},
        "end": {"dateTime": end_time.isoformat(), "timeZone": "UTC"},
    }
    event_result = calendar_service.events().insert(calendarId=CALENDAR_ID, body=event).execute()
    return event_result["htmlLink"]
import os
import json
from datetime import datetime, timedelta
from google.oauth2 import service_account
from googleapiclient.discovery import build

# Load credentials (from file locally, from env in production)
if os.path.exists("service_account.json"):
    credentials = service_account.Credentials.from_service_account_file(
        "service_account.json",
        scopes=["https://www.googleapis.com/auth/calendar"]
    )
else:
    service_account_info = json.loads(os.environ["SERVICE_ACCOUNT_JSON"])
    credentials = service_account.Credentials.from_service_account_info(
        service_account_info,
        scopes=["https://www.googleapis.com/auth/calendar"]
    )

# Build calendar service
calendar_service = build("calendar", "v3", credentials=credentials)


CALENDAR_ID = "jhasneha344@gmail.com"

def check_availability(start_time: datetime, duration_minutes: int = 30):
    end_time = start_time + timedelta(minutes=duration_minutes)
    body = {
        "timeMin": start_time.isoformat() + "Z",
        "timeMax": end_time.isoformat() + "Z",
        "items": [{"id": CALENDAR_ID}]
    }
    events = calendar_service.freebusy().query(body=body).execute()
    busy = events["calendars"][CALENDAR_ID]["busy"]
    return not busy  # True if available

def book_appointment(start_time: datetime, summary="TailorTalk Appointment", duration_minutes=30):
    end_time = start_time + timedelta(minutes=duration_minutes)
    event = {
        "summary": summary,
        "start": {"dateTime": start_time.isoformat(), "timeZone": "UTC"},
        "end": {"dateTime": end_time.isoformat(), "timeZone": "UTC"},
    }
    event_result = calendar_service.events().insert(calendarId=CALENDAR_ID, body=event).execute()
    return event_result["htmlLink"]