# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUUswv5HEdzx8qj__yhWpPkrj5UDhrp5
"""

from fastapi import FastAPI, Form
from fastapi.middleware.cors import CORSMiddleware
from agent import chat_with_agent

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow frontend
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/chat")
async def chat(input: str = Form(...)):
    response = chat_with_agent(input)
    return {"response": response}